Fix for mac users
visualcurrent/Notion-2-Obsidan pull request #4
Opened 2020-10-20 13:18 UTC by rapatel0

On macs you cannot select any files because they are greyed out. 

This fixes it.

2021-01-28 21:49 UTC, lkaratun commented
I came to pull requests intending to submit this same fix :D

2021-01-28 21:50 UTC, lkaratun requested changes

2021-01-28 21:50 UTC, lkaratun commented on N2O.py
> +NotionZip = Path(fileopenbox(iletypes = ['*.zip']))
This looks like a typo: should be `filetypes` not `iletypes`

2021-01-30 05:02 UTC, visualcurrent reviewed
I didn't approve the merge directly because of the typo. 

Thank you @rapatel0 for adding this nuance. Thank you @lkaratun for pointing out the typo. Combined, I've made the change in the master.

2021-01-30 05:07 UTC, closed without merging